export const businessInfo = {
  name: "TechBuddy by Victor",
  owner: "Victor Licona",
  phone: "(817) 470-4724",
  phoneHref: "tel:+18174704724",
  email: "general@techbuddybyvictor.com",
  emailHref: "mailto:general@techbuddybyvictor.com",
  domain: "techbuddybyvictor.com",
  businessType: "Local Technology Support & IT Services",
  serviceArea: "Fort Worth, Texas",
  nearbyAreas: [
    "Sansom Park",
    "River Oaks",
    "White Settlement",
    "Northside",
    "Lake Worth",
    "West Fort Worth",
    "Surrounding areas",
  ],
  categories: [
    "Tech Support",
    "Computer Repair",
    "Wi-Fi & Networking",
    "Smart Home Setup",
    "Small Business Technology Support",
    "Mobile Device Support",
    "Remote Tech Support",
  ],
  bookingTypes: ["On-site appointments", "Remote support", "Small business support", "Scheduled visits"],
  paymentMethods: ["Cash", "Zelle", "Cash App", "Apple Pay", "Credit/Debit Cards"],
};
